name: "Update Package.json"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version: Unity Package Version you want update to. (sample 1.0.0)"
        required: true
      dry_run:
        description: "dry_run: true will never create commit/pr."
        required: true
        default: "false"

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      TARGET_FILE: ./src/MagicOnion.Client.Unity/Assets/Scripts/MagicOnion/package.json
      DRY_RUN: ${{ github.event.inputs.dry_run }}
    steps:
      - uses: actions/checkout@v2
      - name: before
        run: cat ${{ env.TARGET_FILE}}
      - name: update package.json to version ${{ env.VERSION }}
        run: sed -i -e "s/\(\"version\":\) \"\(.*\)\",/\1 \"${{ env.VERSION }}\",/" ${{ env.TARGET_FILE }}
      - name: after
        run: cat ${{ env.TARGET_FILE}}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "feat: Update package.json to ${{ env.VERSION }}" -a
        if: env.DRY_RUN == 'false'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        if: env.DRY_RUN == 'false'
